#!/usr/bin/env python3
"""Prepare a fresh BasketCorp Godot 4.5.1 iOS Release export outside this repo.

Usage: python3 tools/ios_prepare_release.py /absolute/path/to/exported/ios
Export first with --export-release "iOS Release" and output BasketCorp.ipa.
The preset exports project files only. This tool never builds, signs or stages.
Pinned fingerprints intentionally reject template/configuration drift; review
and test a template upgrade rather than weakening the guard or copying a pbxproj.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import re
import struct
import subprocess
import sys
import xml.etree.ElementTree as ET

SOURCE = "client/godot/assets/images/BasketCorp_AppIcon_Base_1024.png"
SOURCE_SHA256 = "5237c6ee5546bfe233737d340c8f8784135115f5d587c3223616f07179de559e"
TARGET_ID = "D0BCFE3318AEBDA2004A7AAE"
OLD_TARGET_ID = "A340BDFEBCA49239A941883D"
LANDSCAPE = ["UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"]
ALL_ORIENTATIONS = LANDSCAPE + ["UIInterfaceOrientationPortrait", "UIInterfaceOrientationPortraitUpsideDown"]
FILES = {
    "export": "BasketCorp/export_options.plist",
    "scheme": "BasketCorp.xcodeproj/xcshareddata/xcschemes/BasketCorp.xcscheme",
    "pbx": "BasketCorp.xcodeproj/project.pbxproj",
    "plist": "BasketCorp/BasketCorp-Info.plist",
    "english": "BasketCorp/en.lproj/InfoPlist.strings",
}
# Canonicalized five-file fingerprints from the audited export, not user files.
# Godot 4.5.1 ios.zip SHA256:
# 4b30d6b49eada4dc0ae9f5301c142b62fcb16f495168f261df3fea433c0af637
EXPECTED_NATIVE = {'export': 'f7da1f67e33cd5aa3f7404c089a6db84fc9c58d9a2ea225f11627656e3f27dda',
 'scheme': '1351174c6103c159277af8c9c6b40429571c9f38e19b97fad292c89922941a59',
 'pbx': '286e096dd38ae494eefab972aacad16294e19a82645841532d341b4baeb3fda5',
 'plist': 'c805d6e77037a75b4aebbd88e4f688ccc2e3491cb07ff45a6a6bc56e1b4db8c4',
 'english': '48063fb8c3a87775aea35f4f1ed8294a262c62c19b1e0206312efbeb98fcb8cc'}
# Audited Release libraries prove this is not a renamed Debug export.
EXPECTED_ENGINE = {'BasketCorp.xcframework/Info.plist': '7ef77af3b98ca82495892b12603e163c2795e19f157e80663e734e68b6e0f9f9',
 'BasketCorp.xcframework/ios-arm64_x86_64-simulator/libgodot.a': '9e7cd344d43dc956f76183e444f4245fb4fc80ee9e28bff67f76d7f7a31514f1',
 'BasketCorp.xcframework/ios-arm64/libgodot.a': 'b377e0d1281c746adbb3a10bccee029bb079957de7ab4bba8040dc5b8371b5bc'}
# Generated by Godot Lanczos from SOURCE; no icon writes are permitted here.
EXPECTED_ICONS = {'Icon-58.png': [58, '6f94f56c0eee736c2d630371d2507f80d2864a52204a86474ab0cb033b7f05af'],
 'Icon-87.png': [87, '3a0099e936a67c574647d977fc7be405827711ec7ede39603091f7d2bfe8d984'],
 'Icon-40.png': [40, 'd1adfa585824ed9ec95e1c8a41ab1b3957e904096acb933a46209a5d5b568d62'],
 'Icon-60.png': [60, 'c5ea7afccecf316590c70ad29d4a4a5910b1787390029a13744ca8004807461f'],
 'Icon-76.png': [76, '63cd10158fce8ff396f9865d606e57e6d8760e9a760721ae47eac0ccb1c901de'],
 'Icon-114.png': [114, '50165cdc614f78057bdca32cbe5c5e6a026a12cef22a5da2a34da08adae6eab2'],
 'Icon-80.png': [80, '2b728f68068c13f80b84f0c8c8b792c786fd5f12389074c2ecec8cf339d3ec7e'],
 'Icon-120.png': [120, '2c4196a13b5b7906d0362d5682af19e1af98a4db0d0bb72982f4765f2d704e3f'],
 'Icon-120-1.png': [120, '2c4196a13b5b7906d0362d5682af19e1af98a4db0d0bb72982f4765f2d704e3f'],
 'Icon-180.png': [180, '9336cd8115ad92440a729f9004c93cc25aa30e8cdf79ae4f2001777d3cd8bc52'],
 'Icon-167.png': [167, '956897b87eea0b9d4fb79f3090a087c78209b28d73c51042d84c90f5dfcb717d'],
 'Icon-152.png': [152, 'e761f039c4d648708b7f17bdd1232c34d70a6a87e1109c79c4d918c057c2c069'],
 'Icon-128.png': [128, 'b4d746b053193d61fabb2d5b3c8500cdecb95998539923b59151a808e3a605a9'],
 'Icon-192.png': [192, '321d407297bca8b5cb272b185026d246b325a4ca41271ea5a4f3692bfdd3da44'],
 'Icon-136.png': [136, '4371e914a150ff7a3d0612e4db19de9b202b761c5e13ae1318d6f2344f53d7f5'],
 'Icon-1024.png': [1024, '5237c6ee5546bfe233737d340c8f8784135115f5d587c3223616f07179de559e']}


class InvalidExport(Exception):
    pass


def require(condition, message):
    if not condition:
        raise InvalidExport(message)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def file_sha(path):
    with path.open("rb") as handle:
        result = hashlib.sha256()
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            result.update(chunk)
        return result.hexdigest()


def inventory(root):
    """Include files, modes and directories; never follow an export symlink."""
    result = {}
    for parent, dirs, files in os.walk(root, followlinks=False):
        for name in sorted(dirs + files):
            path = Path(parent) / name
            require(not path.is_symlink(), f"Symlink refused: {path}")
            mode = path.stat().st_mode
            if path.is_dir():
                result[str(path.relative_to(root))] = ["directory", mode]
            else:
                require(path.is_file(), f"Non-regular file refused: {path}")
                result[str(path.relative_to(root))] = [file_sha(path), mode]
    return result


def replace_exact(text, old, new, count, label):
    require(text.count(old) + text.count(new) == count,
            f"{label}: expected {count} old/already-correct occurrences")
    return text.replace(old, new)


def transform(role, text):
    """Text substitutions only: no document serialization or formatting."""
    if role == "export":
        data = plistlib.loads(text.encode())
        require(data.get("method") in ("app-store", "app-store-connect"),
                "Release export method must be app-store or app-store-connect")
        require(data.get("teamID") == "2T3222NW4Y", "Unexpected export Team")
        return replace_exact(text, "<string>app-store</string>",
                             "<string>app-store-connect</string>", 1, "method")
    if role == "scheme":
        tree = ET.fromstring(text)
        refs = list(tree.iter("BuildableReference"))
        require(len(refs) == 4, "Expected exactly four scheme references")
        for ref in refs:
            require(ref.get("BlueprintIdentifier") in (OLD_TARGET_ID, TARGET_ID)
                    and ref.get("BlueprintName") == "BasketCorp"
                    and ref.get("BuildableName") == "BasketCorp.app"
                    and ref.get("ReferencedContainer") == "container:BasketCorp.xcodeproj",
                    "Unexpected scheme target reference")
        text = replace_exact(text, f'BlueprintIdentifier = "{OLD_TARGET_ID}"',
                             f'BlueprintIdentifier = "{TARGET_ID}"', 4, "scheme IDs")
        for action, config in [("LaunchAction", "Debug"), ("TestAction", "Debug"),
                               ("ProfileAction", "Debug"), ("AnalyzeAction", "Debug"),
                               ("ArchiveAction", "Release")]:
            pattern = rf'(<{action}\b[^>]*\bbuildConfiguration = ")(Debug|Release)(")'
            text, count = re.subn(pattern, lambda m: m[1] + config + m[3], text)
            require(count == 1, f"Unexpected {action} configuration")
        return text
    if role == "pbx":
        return replace_exact(text, 'INFOPLIST_KEY_CFBundleDisplayName = "BasketManager_Web";',
                             'INFOPLIST_KEY_CFBundleDisplayName = "BasketCorp";', 2, "display names")
    if role == "plist":
        data = plistlib.loads(text.encode())
        require(data.get("UISupportedInterfaceOrientations") in (LANDSCAPE, ALL_ORIENTATIONS),
                "Unexpected iPhone orientations")
        require(data.get("UISupportedInterfaceOrientations~ipad") == ALL_ORIENTATIONS,
                "Unexpected iPad orientations; refusing to change them")
        pattern = r'(<key>UISupportedInterfaceOrientations</key>\s*<array>).*?(</array>)'
        body = "\n" + "".join(f"\t\t<string>{v}</string>\n" for v in LANDSCAPE) + "\t"
        text, count = re.subn(pattern, lambda m: m[1] + body + m[2], text, flags=re.S)
        require(count == 1, "Expected exactly one iPhone orientation array")
        return text
    if role == "english":
        return replace_exact(text, 'CFBundleDisplayName = "BasketManager_Web";',
                             'CFBundleDisplayName = "BasketCorp";', 1, "English display name")
    raise InvalidExport(f"Role outside allowlist: {role}")


def validate_native(data):
    """Check actual target settings without rewriting the OpenStep plist."""
    process = subprocess.run(["plutil", "-convert", "json", "-o", "-", "--", "-"],
                             input=data["pbx"], capture_output=True)
    require(process.returncode == 0, "Invalid pbxproj: " + process.stderr.decode(errors="replace"))
    objects = json.loads(process.stdout)["objects"]
    targets = [k for k, v in objects.items() if v.get("isa") == "PBXNativeTarget"]
    require(targets == [TARGET_ID], "Unexpected native target(s)")
    target = objects[TARGET_ID]
    require(target["name"] == "BasketCorp", "Wrong target name")
    config_ids = objects[target["buildConfigurationList"]]["buildConfigurations"]
    configs = {objects[k]["name"]: objects[k]["buildSettings"] for k in config_ids}
    require(set(configs) == {"Debug", "Release"} and len(config_ids) == 2,
            "Expected Debug and Release target configurations")
    expected = {
        "ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon", "DEVELOPMENT_TEAM": "2T3222NW4Y",
        "PRODUCT_BUNDLE_IDENTIFIER": "com.isibosch.basketcorp", "PRODUCT_NAME": "BasketCorp",
        "EXECUTABLE_NAME": "BasketCorp", "MARKETING_VERSION": "1.0.0",
        "CURRENT_PROJECT_VERSION": "1.0.0", "IPHONEOS_DEPLOYMENT_TARGET": "15.0",
        "ARCHS": "arm64", "TARGETED_DEVICE_FAMILY": "1,2", "CODE_SIGN_STYLE": "Automatic",
        "CODE_SIGN_IDENTITY": "Apple Development", "CODE_SIGN_IDENTITY[sdk=iphoneos*]": "Apple Development",
        "INFOPLIST_FILE": "BasketCorp/BasketCorp-Info.plist",
    }
    for name, settings in configs.items():
        for key, value in expected.items():
            require(settings.get(key) == value, f"Unexpected {name} {key}: {settings.get(key)!r}")
        require(settings.get("INFOPLIST_KEY_CFBundleDisplayName") in ("BasketManager_Web", "BasketCorp"),
                f"Unexpected {name} display name")
    app = plistlib.loads(data["plist"])
    for key, value in {"CFBundleIdentifier": "$(PRODUCT_BUNDLE_IDENTIFIER)",
                       "CFBundleName": "$(PRODUCT_NAME)",
                       "CFBundleDisplayName": "$(INFOPLIST_KEY_CFBundleDisplayName)",
                       "CFBundleShortVersionString": "$(MARKETING_VERSION)",
                       "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)"}.items():
        require(app.get(key) == value, f"Unexpected Info.plist {key}")


def png(path, size, expected_hash):
    data = path.read_bytes()
    require(sha(data) == expected_hash, f"Unexpected PNG content: {path}")
    require(data[:8] == b"\x89PNG\r\n\x1a\n" and len(data) > 33
            and struct.unpack(">II", data[16:24]) == (size, size)
            and data[24:26] == bytes([8, 2]), f"Expected opaque RGB PNG {size}x{size}: {path}")


def prepare(root):
    repo = Path(__file__).resolve().parent.parent
    require(root.is_absolute(), "Use an explicit absolute export directory")
    require(root.is_dir() and not root.is_symlink(), "Export directory absent or symbolic")
    require(not any(p.is_symlink() for p in [root, *root.parents]), "Symbolic export path refused")
    root = root.resolve()
    require(root != repo and repo not in root.parents, "Export must be outside the source repository")
    require(not (root / ".git").exists() and not (root / "project.godot").exists(),
            "Refusing a source project as export destination")
    before = inventory(root)
    for rel in FILES.values():
        require((root / rel).is_file(), f"Required file missing: {rel}")
    require((root / "BasketCorp.pck").is_file() and (root / "BasketCorp.pck").stat().st_size > 0,
            "Missing exported game pack")
    for rel, digest in EXPECTED_ENGINE.items():
        require(rel in before and before[rel][0] == digest, f"Wrong Godot Release template: {rel}")
    source = repo / SOURCE
    require(source.is_file() and not source.is_symlink(), "Missing canonical source PNG")
    png(source, 1024, SOURCE_SHA256)
    iconset = root / "BasketCorp/Images.xcassets/AppIcon.appiconset"
    require(list(root.glob("**/*.appiconset")) == [iconset], "Unexpected AppIcon catalog(s)")
    contents = json.loads((iconset / "Contents.json").read_bytes())
    entries = contents["images"]
    require(len(entries) == 16 and {v.get("filename") for v in entries} == set(EXPECTED_ICONS),
            "Expected the audited 16 AppIcon entries")
    require({p.name for p in iconset.glob("*.png")} == set(EXPECTED_ICONS), "Unexpected icon PNG files")
    for entry in entries:
        name = entry["filename"]
        size, digest = EXPECTED_ICONS[name]
        require(entry.get("idiom") == "universal" and entry.get("platform") == "ios",
                "Unexpected AppIcon mapping")
        dimensions = [float(v) * float(entry.get("scale", "1x")[:-1]) for v in entry["size"].split("x")]
        require(dimensions == [size, size], f"Wrong AppIcon dimensions: {name}")
        png(iconset / name, size, digest)
    original = {role: (root / rel).read_bytes() for role, rel in FILES.items()}
    validate_native(original)
    planned = {role: transform(role, data.decode("utf-8")).encode("utf-8") for role, data in original.items()}
    for role, data in planned.items():
        require(sha(data) == EXPECTED_NATIVE[role], f"Template drift in {FILES[role]}; no files written")
        require(transform(role, data.decode()).encode() == data, f"Non-idempotent plan: {role}")
    validate_native(planned)
    require(inventory(root) == before, "Export changed during preflight; no files written")
    # All five plans are validated before the first write. Modes are preserved.
    for role, rel in FILES.items():
        if original[role] != planned[role]:
            (root / rel).write_bytes(planned[role])
    after = inventory(root)
    changed = sorted(k for k in before.keys() | after.keys() if before.get(k) != after.get(k))
    allowed = {FILES[role] for role in FILES if original[role] != planned[role]}
    require(set(changed) == allowed, f"Unexpected export change: {changed}")
    for role, rel in FILES.items():
        require((root / rel).read_bytes() == planned[role], f"Post-write mismatch: {rel}")
        require(after[rel][1] == before[rel][1], f"Mode changed: {rel}")
    print(json.dumps({"status": "OK", "export": str(root), "changed": changed,
                      "idempotent_noop": not changed, "outside_allowlist_changes": [],
                      "target_hashes": {rel: {"before": sha(original[role]), "after": sha(planned[role])}
                                        for role, rel in FILES.items()}}, indent=2))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("export_directory", type=Path)
    args = parser.parse_args()
    try:
        prepare(args.export_directory)
    except (InvalidExport, OSError, ValueError, KeyError, TypeError, ET.ParseError) as error:
        print(f"STOP: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
